site_name: Ninefold
site_url: http://help.ninefold.com
site_description: Ninefold - Ruby on Rails hosting and app deployment
dev_addr: '0.0.0.0:8000'
repo_url: https://github.com/ninefold/docs/

# use_directory_urls: true
include_search: true

theme_dir: ./theme/mkdocs/
# theme_center_lead: false
site_favicon: favicon.ico

pages:

# About
- ['index.md', 'Home']

# Getting Started
- ['getstarted/how_to_deploy_an_app.md', 'Getting Started', 'Deploy an app']
- ['getstarted/how_to_install_and_utilize_the_cli.md', 'Getting Started', 'Utilize the CLI']
- ['getstarted/how_to_migrate_from_heroku.md', 'Getting Started', 'Migrating from Heroku']
- ['getstarted/how_ninefold_works_with_github_bitbucket_and_git_url.md', 'Getting Started', 'GitHub, Bitbucket and Git URL']
- ['getstarted/how_to_utilize_ninefold_logging.md', 'Getting Started', 'Ninefold logging']
- ['getstarted/exporting_and_importing_postgresql_data.md', 'Getting Started', 'Exporting and importing PostgreSQL data']
- ['getstarted/how_to_deploy_diaspora.md', 'Getting Started', 'Deploy Diaspora']

# App Deployment
- ['apps/deployment_with_continuous_integration_ci.md', 'App Deployment', 'Deployment with CI']
- ['apps/deploying_a_rails_app_with_your_own_database.md', 'App Deployment', 'Deploying a Rails app with your own database']
- ['apps/unicorn.md', 'App Deployment', 'Setup: Unicorn']
- ['apps/asset_precompile_on_ninefold.md', 'App Deployment', 'Asset precompilation']
- ['apps/setting_up_deployment_notifications.md', 'App Deployment', 'Deployment notifications']
- ['apps/zero_downtime_deployment_for_your_ninefold_rails_app.md', 'App Deployment', 'Zero downtime deployment']
- ['apps/setting_and_changing_your_apps_configuration.md', 'App Deployment', 'App configuration and infrastructure']
- ['apps/private_gem_repos_on_github_and_bitbucket.md', 'App Deployment', 'Private gem repos']
- ['apps/what_happens_and_what_gets_built_on_a_rails_app_deployment.md', 'App Deployment', 'What happens during deployment']
- ['apps/ssl_management_for_rails_apps.md', 'App Deployment', 'SSL for Rails apps']
- ['apps/dns_management_for_rails_apps.md', 'App Deployment', 'DNS management for Rails apps']
- ['apps/setup_elasticsearch.md', 'App Deployment', 'Setup Elasticsearch']
- ['apps/adding_sendgrid_to_your_rails_app.md', 'App Deployment', 'Adding SendGrid']
- ['apps/redisforapps.md', 'App Deployment', 'Redis Setup']
- ['apps/creating_scheduled_tasks_in_rails.md', 'App Deployment', 'Creating scheduled tasks']
- ['apps/backing_up_and_restoring_your_rails_db.md', 'App Deployment', 'Backup and restore your database']
- ['apps/redeploying_an_app.md', 'App Deployment', 'Redeploying an app']
- ['apps/postgres_and_postgis_and_modules.md', 'App Deployment', 'PostgreSQL, PostGIS, and PostgreSQL modules']
- ['apps/how_to_utilize_a_cdn_with_ninefold.md', 'App Deployment', 'How to utilize a CDN']
- ['apps/upgrading_from_rails_40_to_41.md', 'App Deployment', 'Upgrading from Rails 4.0 to 4.1']
- ['apps/faq.md', 'App Deployment', 'FAQ']

# Servers
- ['servers/how_to_create_a_docker_server.md', 'Servers', 'Docker containers']
- ['servers/create.md', 'Servers', 'Create a server']
- ['servers/resize.md', 'Servers', 'Resize your server']
- ['servers/liveview.md', 'Servers', 'Access your server with live view']
- ['servers/how_to_clone_your_server.md', 'Servers', 'Clone a server']
- ['servers/how_to_attach_and_upload_an_iso.md', 'Servers', 'Upload and attach an ISO']
- ['servers/how_to_create_a_template_from_your_server.md', 'Servers', 'Create a template from your server']
- ['servers/moving.md', 'Servers', 'Copying or moving servers between regions']
- ['servers/how_to_add_storage_volumes.md', 'Servers', 'Add storage volumes']
- ['servers/how_to_view_attached_and_detached_storage_volumes.md', 'Servers', 'View attached/detached storage volumes']
- ['servers/how_to_detach_then_reattach_a_storage_volume.md', 'Servers', 'Detach then reattach a storage volume']
- ['servers/using_backups_to_protect_your_data.md', 'Servers', 'Using backups to protect your data']
- ['servers/new_server_username_and_password.md', 'Servers', 'New server username and password']
- ['servers/resetting_server_password.md', 'Servers', 'Reset your server password']
- ['servers/how_to_connect_to_your_server_using_ssh_rdp.md', 'Servers', 'Connect using SSH / RDP']
- ['servers/how_to_activate_windows_server.md', 'Servers', 'Activate Windows Server']
- ['servers/microsoft_licensing_can_i_use_my_existing_software_and_licenses_on_ninefold.md', 'Servers', 'Microsoft licensing']
- ['servers/faq.md', 'Servers', 'FAQ']

# Networking
- ['networking/ninefold_net.md', 'Networking', 'Enable Ninefold Net']
- ['networking/dns_management_for_servers.md', 'Networking', 'DNS management for servers']
- ['networking/setup_load_balancing_single_zone.md', 'Networking', 'Setup load balancing']
- ['networking/setting_up_static_nat_and_port_forward_for_ip_addresses.md', 'Networking', 'Static NAT & port forward']
- ['networking/how_to_open_firewall_ports.md', 'Networking', 'Open firewall ports']
- ['networking/disable_server_os_firewall.md', 'Networking', 'Disable server OS firewall']
- ['networking/how_to_setup_global_load_balancing_for_servers.md', 'Networking', 'Global load balancing']
- ['networking/how_to_delegate_your_domain_to_ninefold.md', 'Networking', 'Delegate your domain']
- ['networking/how_to_release_or_unassign_your_ip_addresses.md', 'Networking', 'How to release or unassign your IP addresses']
- ['networking/how_to_use_multiple_ip_addresses_on_a_server.md', 'Networking', 'How to use multiple IP addresses']

# Accounts and Billing
- ['billing/freetrial.md', 'Accounts & Billing', 'Free trial']
- ['billing/createuser.md', 'Accounts & Billing', 'Creating additional users']
- ['billing/closeaccount.md', 'Accounts & Billing', 'How to close your account']
- ['billing/faq.md', 'Accounts & Billing', 'Billing FAQ']

# Reference
- ['reference/faq.md', 'Reference', 'FAQ']
- ['reference/apdex.md', 'Reference', 'Apdex to measure user satisfaction']
- ['reference/API.md', 'Reference', 'Using the API (v2)']
- ['reference/contributing.md', 'Reference', 'Contribute to our docs']
